### ISSUE TITLE
Support for the ping-heartbeat endpoint

### ISSUE THREAD

**Issue by Korfeusz** [ahonn/keygen-rs#7]
First of all thanks for the crate. I wanted to ask whether you would be open to consider adding heartbeat functionality. This is something that would be great for implementing floating licenses. 

I can write the code, but I wanted to first ask whether the repository would be open to such a contribution? If so, then these are two things to consider:

1. where this functionality should live. I propose creating a new Heartbeat struct with appropriate methods (e.g. start, stop, ping), maybe also implement the From trait to create the Heartbeat from a Machine struct.
2. whether we should just add the single heartbeat-ping call and leave the spawning of a heartbeat-thread to the final implementor, or if it would be ok to also add the spawning of a new thread with a heartbeat loop for easier use.

Another solution that would work for my problem is if client::Client was made fully public, such that I could use it to make my own POST request to keygen.sh without having to essentially write the same reqwest client as is already implemented here.

**Comment by ahonn** [comment]
All contributions are open, and issues and pull requests are welcome.

1. The original design is to implement the basic implementation of keygen.sh in https://github.com/ahonn/keygen-rs/tree/master/src, and then call them in the Tauri plugin. Since this crate is actually imitated from the official https://github.com/keygen-sh/keygen-go implementation, So I recommend that it be implemented in a way that is as consistent as possible with keygen-go (reference https://github.com/keygen-sh/keygen-go）

2. We can provide both methods. You can add the single heartbeat-ping call and then improve it later to add the spawning of a new thread with a heartbeat loop for easier use. The keygen-go mentioned above is also implemented in this way. For details, you can view the test code of this part at https://github.com/keygen-sh/keygen-go/blob/86076085a51417604308080285cd6cc40447f6e8/keygen_test.go#L273C3-L306C39.

If making client::Client fully public helps facilitate the use of functionalities that are not implemented in keygen-rs, then it is useful. PR is welcome as well.
